# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
name: license

steps:
  - name: check
    image: docker.io/library/golang:1.15.2
    pull: always
    commands:
      - go get -u github.com/google/addlicense
      - addlicense -c "SIGHUP s.r.l" -v -l bsd --check .
---
kind: pipeline
name: policeman

depends_on:
  - license

steps:
  - name: lint
    image: quay.io/sighup/policeman
    pull: always
    environment:
      FILTER_REGEX_EXCLUDE: app/static/prism.*
    depends_on:
      - clone

  - name: render
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.19.0_3.6.1_2.4.1
    pull: always
    depends_on:
      - clone
    commands:
      - kustomize build . > gpm.yml

  - name: deprek8ion
    image: eu.gcr.io/swade1987/deprek8ion:1.1.31
    pull: always
    depends_on:
      - render
    commands:
      - /conftest test -p /policies gpm.yml

---
kind: pipeline
name: e2e

depends_on:
  - policeman

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/renovate/*

steps:
  - name: build
    image: docker:dind
    pull: always
    environment:
      CACHE_FROM: quay.io/sighup/gatekeeper-policy-manager:unstable
      CONTAINER_IMAGE_NAME: gatekeeper-policy-manager
      CONTAINER_IMAGE_TAG: test-${DRONE_BUILD_NUMBER}
      DOCKERFILE: Dockerfile
      BUILD_CONTEXT: "."
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker pull $${CACHE_FROM}
      - docker build
        --pull=true
        --rm=true
        --cache-from $${CACHE_FROM}
        -f $${DOCKERFILE}
        -t $${CONTAINER_IMAGE_NAME}:$${CONTAINER_IMAGE_TAG}
        $${BUILD_CONTEXT}

  - name: kind
    image: docker:dind
    pull: always
    environment:
      KIND_VERSION: v0.9.0
      CLUSTER_VERSION: v1.19.1
      LOAD_IMAGE: gatekeeper-policy-manager:test-${DRONE_BUILD_NUMBER}
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - wget -qO /usr/local/bin/kind "https://kind.sigs.k8s.io/dl/$${KIND_VERSION}/kind-$(uname)-amd64"
      - wget -qO /usr/local/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/$${CLUSTER_VERSION}/bin/linux/amd64/kubectl"
      - chmod +x /usr/local/bin/kind /usr/local/bin/kubectl
      - kind create cluster --name $${CLUSTER_NAME} --image kindest/node:$${CLUSTER_VERSION}
      - kind load docker-image $${LOAD_IMAGE} --name $${CLUSTER_NAME}
      - kind get kubeconfig --name $${CLUSTER_NAME} > kubeconfig.yml

  - name: tests
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.19.0_3.6.1_2.4.1
    pull: always
    network_mode: host
    environment:
      KUBECONFIG: /tmp/kubeconfig.yml
      LOAD_IMAGE: gatekeeper-policy-manager:test-${DRONE_BUILD_NUMBER}
    commands:
      - mv kubeconfig.yml $${KUBECONFIG}
      - cd tests
      - kustomize edit set image quay.io/sighup/gatekeeper-policy-manager=$${LOAD_IMAGE}
      - cd -
      - bats -t tests/tests.sh

  - name: kind-destroy
    image: docker:dind
    pull: always
    environment:
      KIND_VERSION: v0.9.0
      LOAD_IMAGE: gatekeeper-policy-manager:test-${DRONE_BUILD_NUMBER}
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker rmi $${LOAD_IMAGE}
      - wget -qO /usr/local/bin/kind "https://kind.sigs.k8s.io/dl/$${KIND_VERSION}/kind-$(uname)-amd64"
      - chmod +x /usr/local/bin/kind
      - kind delete cluster --name $${CLUSTER_NAME}
    when:
      status:
        - success
        - failure

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: release

depends_on:
  - license
  - policeman
  - e2e

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/**
    exclude:
      - refs/heads/renovate/*

steps:
  - name: registry-sha
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      registry: quay.io
      repo: quay.io/sighup/gatekeeper-policy-manager
      cache_from:
        - quay.io/sighup/gatekeeper-policy-manager:unstable
      tags:
        - ${DRONE_COMMIT_SHA}
        - unstable
    when:
      event:
        - push

  - name: registry-tag
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      registry: quay.io
      repo: quay.io/sighup/gatekeeper-policy-manager
      cache_from:
        - quay.io/sighup/gatekeeper-policy-manager:unstable
      tags:
        - ${DRONE_TAG}
        - latest
    when:
      event:
        - tag
